version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: heriol  # Remplacez ceci par le mot de passe de l'utilisateur root.
      MYSQL_DATABASE: dump
      MYSQL_USER: heriol # Remplacez ceci par le nom de votre utilisateur, différent de l'utilisateur root par défaut.
      MYSQL_PASSWORD: monSuperMotDePasse123! # Remplacez ceci par le mot de passe de votre utilisateur, différent du mot de passe par défaut de l'utilisateur root.
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "heriol", "--password=monSuperMotDePasse123!"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: fastapi-backend
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: dump
      DB_USER: heriol # Remplacez ceci par le nom de votre utilisateur, différent de l'utilisateur root par défaut.
      DB_PASSWORD: monSuperMotDePasse123! # Remplacez ceci par le mot de passe de votre utilisateur, différent du mot de passe par défaut de l'utilisateur root.

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  dbdata:
